# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: 
     - '**.jpeg'
     - '**.jpg'
     - '**.png'
     - '**.gif'
     - '**.JPEG'
     - '**.JPG'
     - '**.PNG'
     - '**.GIF'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
         python-version: '3.x'

      - name: Install dependencies
        run: |
             python -m pip install --upgrade pip
             pip install Pillow

      - name: Update Catalog
        run: |
             git config --global user.name "github-actions[bot]"
             git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
             git pull

      - name: execute py script
        run: python wallpapers-indexer.py

      - name: Commit and Push
        run: |
             git config --global user.name "github-actions[bot]"
             git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
             git add -A
             git commit -m "Automata index készítő"
             git push
